#!/usr/bin/env bash

# IMPORTANT: This script must be called from the root of parent repo (ie, the
# repo in which this repo lives as git submodule).

main() {

  if ! [ -f .make_codeclimate ]; then
    echo "Adding default .make_codeclimate, since none exists."
    echo ""
    echo "*********************************************************************"
    echo "WARNING: Edit .make_codeclimate and re-run this script to add"
    echo "         support for ruby or rails."
    echo "*********************************************************************"
    echo ""
    cp conjur-project-config/files/codeclimate/.make_codeclimate .
    chmod +x .make_codeclimate
  fi

  echo "Assemble .codeclimate.yml using .make_codeclimate."
  ./.make_codeclimate > .codeclimate.yml
  echo "Done."
  echo ""

  echo "Add or update Rubocop settings files."

  cp conjur-project-config/files/rubocop/.rubocop.yml .
  cp conjur-project-config/files/rubocop/.rubocop_settings.yml .

  if ! [ -f .rubocop_todo.yml ]; then
    echo "   - Add blank .rubocop_todo, since none exists."
    echo ""
    cp conjur-project-config/files/rubocop/.rubocop_todo.yml .
  fi
  echo "Done."
  echo ""

  echo "Run 'git status' to see if what changed, if anything."
  echo ""
}

main
